- name: Download Tomcat
  get_url:
    url: http://ftp.unicamp.br/pub/apache/tomcat/tomcat-9/v9.0.22/bin/apache-tomcat-9.0.22.tar.gz
    dest: /tmp/apache-tomcat-9.0.22.tar.gz

- name: Extract Tomcat to folder opt
  unarchive:
    src: /tmp/apache-tomcat-9.0.22.tar.gz
    dest: /opt
    remote_src: yes