# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "forwarded_port", guest: 8282, host: 8282
  config.vm.network :private_network, ip: "192.168.58.111"

  config.vm.provision "shell",
    privileged: false,
    inline: "bash /vagrant/install_dependencies.sh"

  config.vm.provision "shell",
    privileged: false,
    inline: "nohup bash /vagrant/start.sh &> /home/vagrant/nohup.grid.out&"

end