version: '3'
services:
  twitter-service:
    build: ./twitter-service
    ports:
      - "8181:8181"
  github-service:
    build: ./github-service
    ports:
      - "8282:8282"
  aggregator-service:
    build: ./aggregator-service
    ports:
      - "8080:8080"
    network_mode: host

